learning_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lesson/', include('lesson.urls', namespace='lesson'))
]

lesson/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'lesson'

urlpatterns = [
    # path('', views.all_materials, name='all_materials'),
    path('', views.MaterialListView.as_view(), name='all_materials'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>',
         views.material_details, name='material_details'),
    path('<int:material_id>/share/', views.share_material,
         name='share_material'),
    path('create/', views.create_form, name='create_form'),
    # path('login/', views.user_login, name='login'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

lesson/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class Material(models.Model):

    MATERIAL_TYPE = (
        ('theory', 'Theoretical Material'),
        ('practice', 'Practical'),

    )
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    body = models.TextField()

    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    publish = models.DateTimeField(default=timezone.now)

    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='user_materials')

    material_type = models.CharField(max_length=20,
                                     choices=MATERIAL_TYPE,
                                     default='theory')

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse('lesson:material_details',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])

lesson/forms.py
from django import forms

from . import models


class EmailMaterialForm(forms.Form):
    name = forms.CharField(max_length=20)
    my_email = forms.EmailField()
    to_email = forms.EmailField()
    comment = forms.CharField(required=False,
                              widget=forms.Textarea)


class MaterialForm(forms.ModelForm):
    class Meta:
        model = models.Material
        fields = ('title', 'body', 'material_type')


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

lesson/views.py
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView

from . import forms
from . import models

# Create your views here.

BODY_TEMPLATE = (
    '{title} at {uri} war recommended to you by {name}.\n\n'
    'Comment: {comment}'
)


class MaterialListView(LoginRequiredMixin, ListView):
    queryset = models.Material.objects.all
    context_object_name = 'materials'
    template_name = 'materials/all_materials.html'


def all_materials(request):
    material_list = models.Material.objects.all()
    return render(request,
                  'materials/all_materials.html',
                  {'materials': material_list})


@login_required
def material_details(request, year, month, day, slug):
    material = get_object_or_404(models.Material,
                                 slug=slug,
                                 publish__year=year,
                                 publish__month=month,
                                 publish__day=day)
    return render(request,
                  'materials/detail.html',
                  {'material': material})


def share_material(request, material_id):
    material = get_object_or_404(models.Material,
                                 id=material_id, )
    sent = False

    if request.method == 'POST':
        form = forms.EmailMaterialForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            material_uri = request.build_absolute_uri(material.get_absolute_url())
            body = BODY_TEMPLATE.format(title=material.title,
                                        uri=material_uri,
                                        name=cd['name'],
                                        comment=cd['comment'])
            subject = '{name}({email}) recommends you {title}'.format(
                name=cd['name'],
                email=cd['my_email'],
                title=material.title
            )
            send_mail(subject, body, 'admin@mysite.com', (cd['to_email'],))
            sent = True
    else:
        form = forms.EmailMaterialForm()

    return render(request,
                  'materials/share.html',
                  {'material': material,
                   'form': form,
                   'sent': sent})


def create_form(request):
    if request.method == 'POST':
        material_form = forms.MaterialForm(request.POST)
        if material_form.is_valid():
            new_material = material_form.save(commit=False)
            new_material.author = User.objects.first()
            new_material.slug = new_material.title.replace(' ', '-')
            new_material.save()
            return render(request,
                          'materials/detail.html',
                          {'material': new_material})

    else:
        material_form = forms.MaterialForm()

    return render(request,
                  'materials/create.html',
                  {'form': material_form})


def user_login(request):
    if request.method == 'POST':
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                username=cd['username'],
                password=cd['password']
            )
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Logged in!!!')
                else:
                    return HttpResponse('not active')
            else:
                return HttpResponse('bad credentials')
    else:
        form = forms.LoginForm()
        return render(request, 'login.html', {'form': form})

lesson/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} DEFAULT TITLE {% endblock %}</title>
    <link href="{% static 'styles.css' %}" rel="stylesheet">
</head>
<body>
{% if request.user.is_authenticated %}
    HI {{ request.user.first_name }}
    <a href="{% url 'lesson:logout' %}">Logout</a>
{% else %}
    <a href="{% url 'lesson:login' %}">Login</a>
{% endif %}
{% block content %}
{% endblock %}
</body>
</html>

lesson/templates/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block content %}
    <h2>User login</h2>
    <form action="." method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Login">
    </form>
{% endblock %}

lesson/templates/materials/all_materials.html
{% extends 'base.html' %}

{% block title %}
Material list
{% endblock %}

{% block content %}
    <h1>My Materials List</h1>
    {% for material in materials %}
    <h2>
        <a href="{{ material.get_absolute_url }}">
            {{ material.title }}
        </a>
    </h2>
    <p>
        Material author: {{material.author}}. Published {{ material.publish }}
    </p>
    <p>
        {{ material.body|truncatewords_html:5|linebreaks }}
    </p>

    {% endfor %}
    <p>
        <a href="{% url 'lesson:create_form' %}">Create New Material</a>
    </p>
{% endblock %}

lesson/templates/materials/create.html
{% extends 'base.html' %}

{% block title %} Create material {% endblock %}

{% block content %}
    <h2>Create new material</h2>
    <form action="." method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Create material">
    </form>

{% endblock %}

lesson/templates/materials/detail.html
{% extends 'base.html' %}

{% block title %} {{ material.title }} {% endblock %}

{% block content %}
    <a href="{% url 'lesson:all_materials' %}">All materials</a>
    <h1>{{ material.title }}</h1>
    <p>
        {{ material.body|linebreaks }}
    </p>
    <i>
        Material author: {{material.author}}. Published {{ material.publish }}
    </i>
    <p>
        <a href="{% url 'lesson:share_material' material.id %}">SHARE</a>
    </p>

{% endblock %}

lesson/templates/materials/share.html
{% extends 'base.html' %}

{% block title %} Share material {% endblock %}

{% block content %}
    {% if sent %}
        <p>{{ material.title }} has been sent</p>
    {% else %}
        <h2>Share {{material.title}} via e-mail</h2>
        <form action="." method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send !">
        </form>
    {% endif %}


{% endblock %}